/**
 * @file bsp_uart.c
 * @brief UART0 DMA 收发与 UART1 阻塞接收实现
 */

#include "bsp_uart.h"
#include "ti_msp_dl_config.h"

/**
 * @brief UART0 DMA channel IDs generated by SysConfig.
 */
#define UART0_TX_DMA_CH    DMA_UART0Tx_CHAN_ID
#define UART0_RX_DMA_CH    DMA_UART0Rx_CHAN_ID

static volatile uint8_t rx_buf[BSP_UART_RX_BUF_SIZE];
static volatile uint32_t rx_done;
static volatile uint32_t rx_read;

static volatile uint8_t tx_buf[BSP_UART_TX_BUF_SIZE];
static volatile uint16_t tx_head;
static volatile uint16_t tx_tail;
static volatile uint16_t tx_dma_len;
static volatile uint8_t tx_busy;

/**
 * @brief 配置并启动一轮 UART0 RX DMA
 */
static void uart_rx_start_dma(void)
{
    DL_DMA_disableChannel(DMA, UART0_RX_DMA_CH);
    DL_DMA_setSrcAddr(DMA, UART0_RX_DMA_CH,
                      (uint32_t)&UART_0_INST->RXDATA);
    DL_DMA_setDestAddr(DMA, UART0_RX_DMA_CH,
                       (uint32_t)&rx_buf[0]);
    DL_DMA_setTransferSize(DMA, UART0_RX_DMA_CH,
                           BSP_UART_RX_BUF_SIZE);
    DL_DMA_enableChannel(DMA, UART0_RX_DMA_CH);
}

/**
 * @brief 获取 RX DMA 已写入的累计字节数
 * @return 包含当前未满DMA块的累计字节数
 */
static uint32_t uart_rx_total(void)
{
    uint32_t done_a;
    uint32_t done_b;
    uint16_t remain;

    do {
        done_a = rx_done;
        remain = DL_DMA_getTransferSize(DMA, UART0_RX_DMA_CH);
        done_b = rx_done;
    } while (done_a != done_b);

    return done_a + BSP_UART_RX_BUF_SIZE - remain;
}

/**
 * @brief 启动 UART0 TX 环形缓冲区中的下一段DMA发送
 */
static void uart_tx_start_dma(void)
{
    uint16_t len;

    if ((tx_busy != 0U) || (tx_head == tx_tail)) {
        return;
    }

    if (tx_head > tx_tail) {
        len = (uint16_t)(tx_head - tx_tail);
    } else {
        len = (uint16_t)(BSP_UART_TX_BUF_SIZE - tx_tail);
    }

    tx_busy = 1U;
    tx_dma_len = len;

    DL_DMA_disableChannel(DMA, UART0_TX_DMA_CH);
    DL_DMA_setSrcAddr(DMA, UART0_TX_DMA_CH,
                      (uint32_t)&tx_buf[tx_tail]);
    DL_DMA_setDestAddr(DMA, UART0_TX_DMA_CH,
                       (uint32_t)&UART_0_INST->TXDATA);
    DL_DMA_setTransferSize(DMA, UART0_TX_DMA_CH, len);
    DL_DMA_enableChannel(DMA, UART0_TX_DMA_CH);
}

void BSP_Uart_Init(void)
{
    DL_DMA_disableChannel(DMA, UART0_TX_DMA_CH);
    DL_DMA_disableChannel(DMA, UART0_RX_DMA_CH);

    /* UART DMA_DONE 中断已经足够，关闭未使用的 DMA 控制器通道中断。 */
    DL_DMA_disableInterrupt(DMA, DL_DMA_INTERRUPT_CHANNEL0);
    DL_DMA_clearInterruptStatus(DMA, DL_DMA_INTERRUPT_CHANNEL0);

    rx_done = 0U;
    rx_read = 0U;
    tx_head = 0U;
    tx_tail = 0U;
    tx_dma_len = 0U;
    tx_busy = 0U;

    /* UART0 只保留DMA完成中断，FIFO数据搬运全部交给DMA。 */
    DL_UART_Main_disableInterrupt(UART_0_INST,
        DL_UART_MAIN_INTERRUPT_TX |
        DL_UART_MAIN_INTERRUPT_RX |
        DL_UART_MAIN_INTERRUPT_RX_TIMEOUT_ERROR |
        DL_UART_MAIN_INTERRUPT_OVERRUN_ERROR |
        DL_UART_MAIN_INTERRUPT_BREAK_ERROR |
        DL_UART_MAIN_INTERRUPT_PARITY_ERROR |
        DL_UART_MAIN_INTERRUPT_FRAMING_ERROR |
        DL_UART_MAIN_INTERRUPT_NOISE_ERROR);
    DL_UART_Main_enableInterrupt(UART_0_INST,
        DL_UART_MAIN_INTERRUPT_DMA_DONE_RX |
        DL_UART_MAIN_INTERRUPT_DMA_DONE_TX);

    DL_UART_Main_enableDMAReceiveEvent(
        UART_0_INST, DL_UART_MAIN_DMA_INTERRUPT_RX);
    DL_UART_Main_enableDMATransmitEvent(UART_0_INST);
    /* 普通 RX DMA 触发需要在收到至少一个字节时产生请求。 */
    DL_UART_Main_setRXFIFOThreshold(
        UART_0_INST, DL_UART_RX_FIFO_LEVEL_ONE_ENTRY);
    DL_UART_Main_clearInterruptStatus(UART_0_INST,
        DL_UART_MAIN_INTERRUPT_DMA_DONE_RX |
        DL_UART_MAIN_INTERRUPT_DMA_DONE_TX);

    NVIC_DisableIRQ(UART_0_INST_INT_IRQN);
    NVIC_ClearPendingIRQ(UART_0_INST_INT_IRQN);
    uart_rx_start_dma();
    NVIC_EnableIRQ(UART_0_INST_INT_IRQN);
}

void BSP_Uart_IRQHandler(void)
{
    switch (DL_UART_Main_getPendingInterrupt(UART_0_INST)) {
        case DL_UART_MAIN_IIDX_DMA_DONE_TX:
            tx_tail = (uint16_t)(tx_tail + tx_dma_len);
            if (tx_tail >= BSP_UART_TX_BUF_SIZE) {
                tx_tail = 0U;
            }
            tx_dma_len = 0U;
            tx_busy = 0U;
            uart_tx_start_dma();
            break;

        case DL_UART_MAIN_IIDX_DMA_DONE_RX:
            rx_done += BSP_UART_RX_BUF_SIZE;
            uart_rx_start_dma();
            break;

        default:
            break;
    }
}

int BSP_Uart_ReadByte(uint8_t *dat)
{
    uint32_t wr;
    uint32_t used;

    if (dat == NULL) {
        return 0;
    }

    wr = uart_rx_total();
    used = wr - rx_read;
    if (used == 0U) {
        return 0;
    }
    if (used > BSP_UART_RX_BUF_SIZE) {
        rx_read = wr - BSP_UART_RX_BUF_SIZE;
    }

    *dat = rx_buf[rx_read % BSP_UART_RX_BUF_SIZE];
    rx_read++;
    return 1;
}

uint16_t BSP_Uart_Write(uint8_t const *buf, uint16_t len)
{
    uint16_t free;
    uint16_t i;
    uint32_t primask;

    if ((buf == NULL) || (len == 0U) ||
        (len > (BSP_UART_TX_BUF_SIZE - 1U))) {
        return 0U;
    }

    primask = __get_PRIMASK();
    __disable_irq();
    if (tx_head >= tx_tail) {
        free = (uint16_t)(BSP_UART_TX_BUF_SIZE - 1U - tx_head + tx_tail);
    } else {
        free = (uint16_t)(tx_tail - tx_head - 1U);
    }
    if (free < len) {
        if (primask == 0U) {
            __enable_irq();
        }
        return 0U;
    }

    for (i = 0U; i < len; i++) {
        tx_buf[tx_head] = buf[i];
        tx_head++;
        if (tx_head >= BSP_UART_TX_BUF_SIZE) {
            tx_head = 0U;
        }
    }
    uart_tx_start_dma();
    if (primask == 0U) {
        __enable_irq();
    }

    return len;
}

int BSP_Uart1_ReadByteBlocking(uint8_t *dat)
{
    if (dat == NULL) {
        return 0;
    }

    while (DL_UART_Main_isRXFIFOEmpty(UART_1_INST) == true) {
    }
    *dat = (uint8_t)DL_UART_Main_receiveData(UART_1_INST);

    return 1;
}
